### ISSUE TITLE
"Adam" optimization

### ISSUE THREAD

**Issue by bashir-sadeghi** [human-analysis/pytorchnet#3]
For "Adam" optimization method, "betas = (.., ..)" can not be set when I try to use "args.txt"
The error I am getting is:
ValueError: too many values to unpack (expected 2)

**Comment by rahmatkhah** [comment]
This issue has been resolved. In order to pass tuple as a parameter, it needs to be passed within double quotes, like so:
optim_options = {"betas": "(0.9, 0.999)"}
