### ISSUE TITLE
Incorrect test accuracy calculation

### ISSUE THREAD

**Issue by michaelklachko** [human-analysis/pytorchnet#6]
You have a serious problem with the way you report test accuracy. This caused incorrect results published in your PNN paper. See https://github.com/michaelklachko/pnn.pytorch for details.

**Comment by vboddeti** [comment]
The problem you refer to does not seem to exist in this repo, so I will close the issue here. Please open an issue on the PNN repo instead. You can re-open here if you think the problem persists in this repo.

**Comment by michaelklachko** [comment]
It does not exist in this repo, and it does not exist in PNN repo, because neither repo includes a method to calculate test dataset accuracy. Instead, PNN paper seems to use your 'running mean" accuracy to report test dataset results. If that's the case, I suggest you add the proper method here to avoid similar problems in the future.

**Comment by michaelklachko** [comment]
Actually, let me take that back: your repo does have this problem. You display "running mean" values during progress bar output, and the last shown accuracy value remains as if it were the test dataset accuracy for that epoch. See the second image in your README.  The per epoch accuracies displayed in that image are not the actual test dataset accuracies, they are smoothed running means, mostly influenced by the accuracy of the last batch. That's why they vary so wildly in that image from epoch to epoch. 

PNN repo, on the other hand, does not display progress bar, but simply prints accuracy for every batch on a separate line (so it's less misleading there). Yet it still seems the values reported in PNN paper used the running mean values (e.g. looking at that image again, you really should not pick 93.75% accuracy from epoch 6 as the best result of your experiment).
